export const BRAND_LIST = [
  {
    name: "almay",
    img_url: "https://i.imgur.com/uiHJsTo.png",
  },
  { name: "alva", img_url: "https://i.imgur.com/CWLQEc0.png" },
  { name: "anna sui", img_url: "https://i.imgur.com/hnzp32p.png" },
  { name: "annabelle", img_url: "https://i.imgur.com/DZF2Uvq.png" },
  { name: "benefit", img_url: "https://i.imgur.com/x5vkf0e.png" },
  { name: "boosh", img_url: "https://i.imgur.com/I5uDA37.png" },
  { name: "burt's bees", img_url: "https://i.imgur.com/1pPbKwk.png" },
  { name: "butter london", img_url: "https://i.imgur.com/dxlLWnY.png" },
  { name: "c'est moi", img_url: "https://i.imgur.com/ObYCbX9.png" },
  { name: "cargo cosmetics", img_url: "https://i.imgur.com/DUQxqzG.png" },
  { name: "china glaze", img_url: "https://i.imgur.com/WEylZ4l.png" },
  { name: "clinique", img_url: "https://i.imgur.com/GWOxqQi.png" },
  {
    name: "coastal classic creation",
    img_url: "https://i.imgur.com/oBnhLRG.png",
  },
  { name: "colourpop", img_url: "https://i.imgur.com/IwRrYtB.png" },
  { name: "covergirl", img_url: "https://i.imgur.com/NR4pPMz.png" },
  { name: "dalish", img_url: "https://i.imgur.com/pxBmNsq.png" },
  { name: "deciem", img_url: "https://i.imgur.com/HIt2nk0.png" },
  { name: "dior", img_url: "https://i.imgur.com/wQq2L8T.png" },
  { name: "dr. hauschka", img_url: "https://i.imgur.com/EaNoL0z.png" },
  { name: "e.l.f.", img_url: "https://i.imgur.com/WNWl1pa.png" },
  { name: "essie", img_url: "https://i.imgur.com/5I7SmEz.png" },
  { name: "fenty", img_url: "https://i.imgur.com/WJuVGSF.png" },
  { name: "glossier", img_url: "https://i.imgur.com/bf9lzr6.png" },
  { name: "green people", img_url: "https://i.imgur.com/5jzZK6Q.png" },
  { name: "https://i.imgur.com/xjb7Jo7.png" },
  { name: "l'oreal", img_url: "https://i.imgur.com/SvGdGWJ.png" },
  { name: "lotus cosmetics usa", img_url: "https://i.imgur.com/NidFGiK.png" },
  { name: "maia's mineral galaxy", img_url: "https://i.imgur.com/vdocVxS.png" },
  { name: "marcelle", img_url: "https://i.imgur.com/7H9D8hw.png" },
  { name: "marienatie", img_url: "https://i.imgur.com/txmMrPZ.png" },
  { name: "maybelline", img_url: "https://i.imgur.com/O7zZBCQ.png" },
  { name: "milani", img_url: "https://i.imgur.com/dN6r0uZ.png" },
  { name: "mineral fusion", img_url: "https://i.imgur.com/6zCY9Rp.png" },
  { name: "misa", img_url: "https://i.imgur.com/tOKUOGZ.png" },
  { name: "mistura", img_url: "https://i.imgur.com/2DNHQpz.png" },
  { name: "moov", img_url: "https://i.imgur.com/njkc8Rv.png" },
  { name: "nudus", img_url: "https://i.imgur.com/EM3fV6I.png" },
  { name: "nyx", img_url: "https://i.imgur.com/6mZpnGP.png" },
  { name: "orly", img_url: "https://i.imgur.com/Z6jat1w.png" },
  { name: "pacifica", img_url: "https://i.imgur.com/TuXTgCw.png" },
  { name: "penny lane organics", img_url: "https://i.imgur.com/GeMLGuj.png" },
  { name: "physicians formula", img_url: "https://i.imgur.com/OjUZPoq.png" },
  { name: "piggy paint", img_url: "https://i.imgur.com/GNVhBxP.png" },
  { name: "pure anada", img_url: "https://i.imgur.com/2VIvFnS.png" },
  { name: "rejuva minerals", img_url: "https://i.imgur.com/Fq759hV.png" },
  { name: "revlon", img_url: "https://i.imgur.com/xLI3B0Z.png" },
  {
    name: "sally b's skin yummies",
    img_url: "https://i.imgur.com/qLVLUvm.png",
  },
  { name: "salon perfect", img_url: "https://i.imgur.com/vSHpOFG.png" },
  { name: "sante", img_url: "https://i.imgur.com/41F1bWD.pn" },
  { name: "sinful colours", img_url: "https://i.imgur.com/rwjxMbi.png" },
  {
    name: "smashbox",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "stila",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "suncoat",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "w3llpeople",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "wet n wild",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "zorah",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
  {
    name: "zorah biocosmetiques",
    img_url: "https://i.imgur.com/rwjxMbi.png",
  },
];
